services:
  hk2:
    default:
      config:
        enabled: "true"
    SystemInjectResolver:
      config:
        enabled: "true"
    HK2TopicDistributionService:
      config:
        enabled: "true"
    DefaultRunLevelContext:
      config:
        enabled: "true"

  jetty.server:
    config:
      enabled: "true"
      host: "localhost"
      context-path: "/"
      port: "0"
      http2:
        enabled: "true"
      # managed services doesn't require class
      #class: "io.descoped.stride.application.server.JettyServerService"

  jersey.objectMapper:
    enabled: "true"

  jersey.server:
    config:
      enabled: true
      # managed services doesn't require class
      #class: "io.descoped.stride.application.server.JerseyServerService"
      mediaTypes:
        yaml: "application/yaml"
        txt: "text/plain"
        schema: "application/schema+json"
        html: "text/html"
        json: "application/json"

  dummy.service:
    config:
      enabled: "false"
      class: "org.jvnet.hk2.annotations.Service"
    metadata:
      foo: "bar"

filters:
  cors:
    config:
      class: "io.descoped.stride.application.cors.ApplicationCORSServletFilter"
      pathSpec: "/*"
      dispatches:
        - "FORWARD"
        - "REQUEST"

servlets:
  admin:
    config:
      class: "io.dropwizard.metrics.servlets.AdminServlet"
      pathSpec: "/admin"
  metrics:
    config:
      class: "io.dropwizard.metrics.servlets.MetricsServlet"
      pathSpec: "/metrics"

resources:
  greeting:
    config:
      class: "io.descoped.stride.application.EmbeddedApplicationTest$GreetingResource"
