package io.descoped.stride.application.core;

import io.descoped.stride.application.StrideApplication;
import io.descoped.stride.application.config.ApplicationConfiguration;
import jakarta.inject.Named;
import jakarta.inject.Singleton;
import org.glassfish.hk2.api.DynamicConfiguration;
import org.glassfish.hk2.api.ServiceLocator;
import org.glassfish.hk2.runlevel.RunLevel;
import org.glassfish.hk2.utilities.BuilderHelper;
import org.glassfish.hk2.utilities.DescriptorImpl;
import org.jvnet.hk2.annotations.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.stream.Stream;

public class ApplicationInitialization {

    private static final Logger log = LoggerFactory.getLogger(ApplicationInitialization.class);
    private final ApplicationConfiguration configuration;
    private final ServiceLocator serviceLocator;

    public ApplicationInitialization(ApplicationConfiguration configuration, ServiceLocator serviceLocator) {
        this.configuration = configuration;
        this.serviceLocator = serviceLocator;
    }

    public StrideApplication initialize() {
        BeanDiscovery beanDiscovery = new BeanDiscovery(configuration, serviceLocator);
        DynamicConfiguration dc = beanDiscovery.getDynamicConfiguration();
        dc.addActiveDescriptor(BuilderHelper.createConstantDescriptor(configuration));

        // register services
        for (io.descoped.stride.application.config.Service service : configuration.services().iterator()) {
            // ignore disabled services
            if (!service.isEnabled()) {
                continue;
            }
            // ignore service without service class
            if (service.className() == null) {
                continue;
            }
            // ignore services generated by hk locator
            if (Stream.of(Singleton.class, Service.class, Named.class).anyMatch(anno -> service.getClass().isAnnotationPresent(anno))) {
                continue;
            }
            DescriptorImpl descriptorImpl = BuilderHelper.link(service.clazz(), true)
                    .to(Service.class)
                    .in(RunLevel.class)
                    .build();
            descriptorImpl.addMetadata(RunLevel.RUNLEVEL_MODE_META_TAG, String.valueOf(RunLevel.RUNLEVEL_MODE_VALIDATING));
            descriptorImpl.addMetadata(RunLevel.RUNLEVEL_VAL_META_TAG, String.valueOf(service.runLevel()));
            //log.trace("--> {}", descriptorImpl);
            dc.bind(descriptorImpl, false);
        }

        // register filters config
        dc.addActiveDescriptor(BuilderHelper.createConstantDescriptor(configuration.filters()));

        // register servlets config
        dc.addActiveDescriptor(BuilderHelper.createConstantDescriptor(configuration.servlets()));

        // register resources config
        dc.addActiveDescriptor(BuilderHelper.createConstantDescriptor(configuration.resources()));

        // create application
        StrideApplication strideApplication = new StrideApplicationImpl(configuration, serviceLocator, beanDiscovery);
        dc.addActiveDescriptor(BuilderHelper.createConstantDescriptor(strideApplication));
        return strideApplication;
    }
}
